# Generated by Django 3.2.7 on 2021-09-24 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prima_wisata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='tempat',
            name='alamat',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Respon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('kategori_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prima_wisata.kategori')),
                ('tempat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prima_wisata.tempat')),
            ],
        ),
        migrations.CreateModel(
            name='Pertanyaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('kategori_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prima_wisata.kategori')),
                ('tempat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prima_wisata.tempat')),
            ],
        ),
    ]
