# Generated by Django 3.2.7 on 2021-09-24 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prima_wisata', '0002_auto_20210924_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='respon',
            name='pertanyaan_id',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='prima_wisata.pertanyaan'),
        ),
    ]
